### ISSUE TITLE
kritis friciton log readme.md and getting-started updates

### ISSUE THREAD

**Issue by aaron-prindle** [grafeas/kritis#108]
tracking issue for kritis friction log notes, feel free to add anything
- [x] adding action items from kritis friction log session:
- [x] add commands for helm service-account perms on GKE
- [x] do not hardcode linux for certgen plugin command, reference platform instead
- [x] if helm has never been run, there is an issue w/ the $HELM_HOME/plugins dir
- [x] try to reduce optional configuration (namespace, secret-name, etc) to reduce first time confustion
- [x] refactor the getting started flow into quickstart=copy-command-get-something-running and using-kritis=more-in-depth
- [x] remove requirements for git clone grafeas-kritis repo to use quickstart (ex: referencing yamls not by url, referencing install.sh from path, etc)

**Comment by aaron-prindle** [comment]
- [ ] document how isps should be used (1 config per namespace)

**Comment by tstromberg** [comment]
I believe this can be closed now, but don't know if what we've done meets what you were looking for.

**Comment by aaron-prindle** [comment]
all points have been addressed, closing
