### ISSUE TITLE
Check if images are fully qualified even if no ISP exists

### ISSUE THREAD

**Issue by priyawadhwa** [grafeas/kritis#110]
Right now the check for fully qualified images happens during ISP validation, but if there are no ISPs deployed then any image (even one that isn't fully qualified) can get through.

We can at least check for fully qualified images without an ISP while kritis is running.

**Comment by tejal29** [comment]
i think this is fine. We only need fully qualified image to get vulnerability info and in future build provenance. 
Once the ISP s deployed, this pod will get labelled appropriately.

**Comment by tejal29** [comment]
Feel free to close, if this makes sense.
