### ISSUE TITLE
identify important isp use cases and verify that multiple isps running yield correct kritis auth

### ISSUE THREAD

**Issue by aaron-prindle** [grafeas/kritis#111]
this issue relates to adding isp integration test cases to kritis.  currently it isn't clear how ISPs should work w/ kritis (one single isp vs multiple) and how repeated images, differing CVE tolerance levels, etc. should work.  We can discuss here what test cases make sense and how kritis should act for each case.

**Comment by tejal29** [comment]
We mention in the Readme, ideally users would want to deploy one ISP per namespace.
