### ISSUE TITLE
Add steps to run and Demo Cron Job.

### ISSUE THREAD

**Issue by tejal29** [grafeas/kritis#120]
1. Add steps to run the cron job from binary.
2. Demo the flow where you 
   a. Deploy a pod with vulnerable image with breakglass annotation  
   b. Remove the annotation with kubectl edit command
   c. Start the cron job with 1 min param
   d. You shd see the annotation added to pod.

**Comment by aaron-prindle** [comment]
I believe this is done, closing

**Comment by tejal29** [comment]
no i  did not submit that PR just closed it. I will re-add the steps.
