### ISSUE TITLE
Gathering metrics for Kritis and creating a dashboard.

### ISSUE THREAD

**Issue by tejal29** [grafeas/kritis#166]
Details are here: 
https://docs.google.com/document/d/1sxYCuj38ZuIN7OQiDTjneS_9rrBHWHeoj3b-ihOdX8g/edit#heading=h.iprw49l6ve10
We need to get the queries to look at these logs.

**Comment by tejal29** [comment]
More on this is on DD.

**Comment by tejal29** [comment]
For release, we can just work on queries and then add a Plx script with dashboard.

**Comment by aaron-prindle** [comment]
3 of the 4 metrics from the DD are now in the dashboard, the only one remaining is the # of blocked pods which might not be feasible

**Comment by aaron-prindle** [comment]
Marking as fixed, the 4th desired metric does not seem feasible
