### ISSUE TITLE
update error message "is not fully qualified" to mention resolve-tags plugin or useful command

### ISSUE THREAD

**Issue by aaron-prindle** [grafeas/kritis#196]
Might make sense to give something actionable to a user instead of "is not fully qualified":
update error message "is not fully qualified" to mention resolve-tags plugin or useful command

**Comment by tejal29** [comment]
The only way a not fully qualified image will be allowed if its whitelisted or has break glass annotation.

I do see a value of adding an actionable message to use "kubectl plugin resolve-tags plugin" both in the admission controller resp and in the annotation.
