### ISSUE TITLE
check for "Controlled By" section before admitting pods

### ISSUE THREAD

**Issue by priyawadhwa** [grafeas/kritis#250]
Right now if we validate and admit a deployment, we validate the pods it creates again. 

It looks like if pods are created by other objects (Deployment, ReplicaSet etc) then there's a "Controlled By" section in the pod description which we could check for before validation. If the "Controlled By" section exists, we can let the pod through (assuming whatever created it was already validating and approved)

```shell
$ kubectl describe pod test-5d54fc85c-bn72b 
Name:           test-5d54fc85c-bn72b
Namespace:      default
Node:           gke-kritis-default-pool-f1c1e77c-n3sw/10.128.0.2
Start Time:     Wed, 15 Aug 2018 10:19:01 -0700
Labels:         pod-template-hash=181097417
                run=test
Annotations:    kubernetes.io/limit-ranger=LimitRanger plugin set: cpu request for container test
Status:         Running
IP:             10.64.2.52
Controlled By:  ReplicaSet/test-5d54fc85c
```

For this to work, we'll need to add:
1. ReplicaSet type to kritis, since Deployments create ReplicaSets which in turn create Pods
2. The actual logic for checking the "Controlled By" section

**Comment by tejal29** [comment]
Nice!
