### ISSUE TITLE
"GCB Signer" signed images fail during GKE attestation checking

### ISSUE THREAD

**Issue by bgeesaman** [grafeas/kritis#282]
Was running the kritis gcb-signer in a cluster roughly 10 days ago, and it was working as expected.  Wednesday/Thursday of last week, the images signed by that gcb-signer (untouched) stopped passing validation by the binauthz API.  The error during pod creation was:

```
Attestation(s) found, but could not be verified. Errors which are not specific to any key follow. No key found for attestation with key id 'kritis-authority-key'
```
The attestation looks like this and no longer works:
```
$ gcloud --project={my-project-name} beta container binauthz attestations list --attestor=kritis-authority1
PGP_KEY_ID                                ARTIFACT_URL
kritis-authority-key                      https://gcr.io/{my-project-name}/mynginx@sha256:3d835762b7f6e3c36e2deeb70f170bb2fddb534c101008dab8f575f1b56e3568
```
After doing some experimentation, the issue appears that the GKE Binauthz API now uses the `PGP_KEY_ID` to look up the PGP KEY by name during image validation.

As a hack to validate, I modified:
```
$ git diff
diff --git a/pkg/kritis/metadata/containeranalysis/containeranalysis.go b/pkg/kritis/metadata/containeranalysis/containeranalysis.go
index abea939..a3e480f 100644
--- a/pkg/kritis/metadata/containeranalysis/containeranalysis.go
+++ b/pkg/kritis/metadata/containeranalysis/containeranalysis.go
@@ -229,10 +229,10 @@ func (c Client) CreateAttestationOccurence(note *grafeas.Note,
        pgpSignedAttestation := &attestation.PgpSignedAttestation{
                Signature: sig,
                KeyId: &attestation.PgpSignedAttestation_PgpKeyId{
-                       PgpKeyId: pgpSigningKey.SecretName,
+                       PgpKeyId: "849EDAC43D1F180476C686DA97C872F4E4490A36",
                },
               ContentType: attestation.PgpSignedAttestation_SIMPLE_SIGNING_JSON,
        }
        attestationDetails := &grafeas.Occurrence_Attestation{
                Attestation: &attestation.Details{
                        Attestation: &attestation.Attestation{
```
And now the image can be deployed in GKE with binauthz requiring that attestation successfully.  The attestations now look like the following with the fingerprint as the `PGP_KEY_ID` field:
```
$ gcloud --project={my-project-name} beta container binauthz attestations list --attestor=kritis-authority1
PGP_KEY_ID                                ARTIFACT_URL
849EDAC43D1F180476C686DA97C872F4E4490A36  https://gcr.io/{my-project-name}/mynginx@sha256:0dccd67d3291afc62278f2d6ff50edfe29d25b53eeea4ead2a117a3c02c9d1c2
kritis-authority-key                      https://gcr.io/{my-project-name}/mynginx@sha256:3d835762b7f6e3c36e2deeb70f170bb2fddb534c101008dab8f575f1b56e3568
```

**Comment by tejal29** [comment]
@wteiken Is this something that changed recently or was always this way.

**Comment by wteiken** [comment]
Yes, the id generated here is actually wrong (it should be the PGP key id), and Binary Authorization recently tightened the checks to be closer to the spec for attestations.  I forgot to also update the generation.

I'll send a fix this afternoon.

**Comment by wteiken** [comment]
Actually the fix is a bit more complex than expected.  Started https://github.com/grafeas/kritis/pull/283

A workaround should be  to use the PGP fingerprint as the secret name.

**Comment by wteiken** [comment]
I think the PR should work to generate the right key id now for the GCB, but it will break the review for the OSS enforcement.

Thanks for the report and the detailed analysis, and apologies for not updating the signer in time.

**Comment by wteiken** [comment]
PR is merged, the attestations created should now work.

Again, apologies for the issue.
