### ISSUE TITLE
Kritis Signer does not work on images with tags

### ISSUE THREAD

**Issue by jianglai** [grafeas/kritis#319]
## Expected Behavior
I followed the Kritis Signer installation guide [here](https://github.com/grafeas/kritis/blob/master/docs/signer_install.md). My Cloud Build [config](https://github.com/jianglai/nomulus/blob/master/cloudbuild-proxy.yaml#L31) applies a tag to the image built (from the git tag that triggers the build).

## Actual Behavior
After receiving the pub/sub message the Kritis Signer successfully validated the provenance of the source code, but failed at creating the attestation with the following error:

```
W0104 20:50:43.195843       1 containeranalysis.go:137] could not parse reference
E0104 20:50:43.196156       1 main.go:57] Error signing: Error creating signature: one or more errors adding attestations: [gcr.io/domain-registry-alpha/proxy:RELEASE-TEST@sha256:cd31542ab0321ac83f997a4fe3053b7f535de54320fd0ebbd2$b9e15fa12b7a7 is not a valid image hosted in GCR] 
```

It looks like the [code](https://github.com/google/go-containerregistry/blob/master/pkg/name/ref.go#L41) the Signer is calling to parse the string validates either it uses a tag format or a hash format, but not both. However the format that Cloud Build send in its pub/sub message contains both.

I tried to have Cloud Build not add the tag to the resulting image and the error went away.

**Comment by iasinDev** [comment]
Hi, I'm having the same problem, please can you tell how did you modified the cloudbuild to not send the problematic format? Thanks in advance!

**Comment by aysylu** [comment]
@jianglai: I'd be happy to review your contribution with the fix in a PR!

**Comment by jianglai** [comment]
@iasinDev I don't recall specifically, I think you can try to not include the tag in the [`images`](https://cloud.google.com/cloud-build/docs/configuring-builds/store-images-artifacts#storing_images_in) section in your GCB config file.

**Comment by iasinDev** [comment]
@jianglai  yes thanks! I pass over by setting in the skkafold the following tag policy:

  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}"

This way GCB create the artifact with just the image name by creating also in the background the "latest" one.

With this when it arrives to kritis through the pubsub notification it doesn't concatenate the tag image, 

Now I'm with another error on next step "creating PGP key: parsing private key: EOF" but this is other thing ... hehe

Thanks!
