### ISSUE TITLE
0.2.0 Release

### ISSUE THREAD

**Issue by aysylu** [grafeas/kritis#369]
Please help the community to prioritize and scope the `0.2.0` release by doing one (or more) of the following:

* Open Kritis GH issue for a feature you'd like to be included and mention in this thread:
  * outline estimated work amount,
  * provide details on whether you'll be able to contribute the feature, if it's prioritized.
* Mention already-filed Kritis GH issues in this thread:
  * outline estimated work amount, if possible,
  * provide details on whether you're able to contribute the feature.
* Upvote the mentioned issues.

**Comment by marco-lancini** [comment]
Hi, is there an ETA on when v0.2.0 will be released?

**Comment by aysylu** [comment]
Hi @marco-lancini, everything is blocked on #414 which is attempting to fix an integration test that potentially reveals a bug. I haven't been able to track down the bug yet, and this week my attention was split between a few projects. I hope to have a better ETA next week. Thanks for your patience!

**Comment by marco-lancini** [comment]
Thank you for letting us know!

**Comment by aysylu** [comment]
This has now been [released](https://groups.google.com/forum/#!topic/kritis-users/RuMzxvoqkhw).
