### ISSUE TITLE
Private key decryption fails when using passphrase

### ISSUE THREAD

**Issue by aysylu** [grafeas/kritis#372]
## Expected Behavior

Private key is correctly decrypted in [code](https://github.com/grafeas/kritis/blob/master/pkg/kritis/secrets/pgpkey.go#L95) when passphrase is provided. 

## Actual Behavior
`NewPgpKey()` fails with `parsing private key: Decrypt failed: openpgp: invalid data: private key checksum failure`.

## Steps to Reproduce the Problem

1.  Set `PHRASE` environment variable:
    ```shell
    PHRASE=passphrase1
    ```
2.  Create public and private key pair with the `passphrase1` as passphrase:
    ```shell
    gpg --quick-generate-key --yes attestor@example.com
    gpg --armor --export attestor@example.com > gpg.pub
    gpg --armor --export-secret-keys attestor@example.com > gpg.priv
    ```
3.  Set the `B64PHRASE` environment variable, which is a `base64` encoding of `PHRASE`:
    ```shell
    B64PHRASE=$( echo ${PHRASE} | base64)
    ```
4.  Create k8s secret in `default` namespace:
    ```shell
    kubectl create secret generic attestor --from-file=public=gpg.pub --from-file=private=gpg.priv --from-literal=passphrase=${B64PHRASE}
    ```

5. `go run` the following program:
    ```go
    package main

    import (
	"log"
        
	"github.com/grafeas/kritis/pkg/kritis/secrets"
    )
    
    func main() {
        s, err := secrets.Fetch("default", "attestor")
        if err != nil {
	    log.Fatal(err)
        }
        log.Printf("Retrieved secret for 'attestor': %v", s)
    }
    ```

**Comment by aysylu** [comment]
Confirmed to fail with the following gpg version on Linux:

```
$ gpg --version
gpg (GnuPG) 2.2.12
libgcrypt 1.8.3
```

**Comment by ooq** [comment]
The bug can be fixed by changing step 3 to `B64PHRASE=$( echo -n ${PHRASE} | base64)`. 

However,  the reproduction step with base4 encoded passphrase in k8s secret should probably be discouraged, as k8s itself does base64 encoding on all fields for uploaded secrets. This issue is tracked at #376.

**Comment by aysylu** [comment]
Thanks, @ooq! The fact that it worked in the gpg `2.2.10` is a bit concerning. I'm closing this issue in favor of #376.

**Comment by ooq** [comment]
Confirmed that gpg `2.2.10` also fails.
