### ISSUE TITLE
kritis.p12: No such file or directory

### ISSUE THREAD

**Issue by codingandcoding** [grafeas/kritis#382]
When I executed ./combined_cert.sh in the standalone folder, I encountered the following problem. How can I solve this problem?

Enter Export Password:
Verifying - Enter Export Password:
Error opening input file kritis.p12
kritis.p12: No such file or directory

./attestation_created.sh
curl: (58) NSS: client certificate not found: grafeas.pem

**Comment by aysylu** [comment]
Good catch, #385 should fix this.
