### ISSUE TITLE
make test: cannot find package

### ISSUE THREAD

**Issue by codingandcoding** [grafeas/kritis#383]
When I run "make test" in the kritis directory, I reported the following error. According to the official documentation, I need to set the GOPATH environment variable, but I have set it in the ~/.bash_profile file according to the official documentation: export GOPATH=$HOME/go.

GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -ldflags "" -tags "" -o out/resolve-tags-linux-amd64 github.com/grafeas/kritis/cmd/kritis/kubectl/plugins/resolve
vendor/github.com/golang/glog/glog.go:74:2: cannot find package "bufio" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/bufio (vendor tree)
	/usr/lib/golang/src/bufio (from $GOROOT)
	/root/go/src/bufio (from $GOPATH)
vendor/github.com/golang/glog/glog.go:75:2: cannot find package "bytes" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/bytes (vendor tree)
	/usr/lib/golang/src/bytes (from $GOROOT)
	/root/go/src/bytes (from $GOPATH)
vendor/github.com/google/go-containerregistry/pkg/v1/v1util/zip.go:19:2: cannot find package "compress/gzip" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/compress/gzip (vendor tree)
	/usr/lib/golang/src/compress/gzip (from $GOROOT)
	/root/go/src/compress/gzip (from $GOPATH)
vendor/github.com/google/go-containerregistry/pkg/v1/hash.go:18:2: cannot find package "crypto/sha256" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/crypto/sha256 (vendor tree)
	/usr/lib/golang/src/crypto/sha256 (from $GOROOT)
	/root/go/src/crypto/sha256 (from $GOPATH)
vendor/gopkg.in/yaml.v2/decode.go:4:2: cannot find package "encoding" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/encoding (vendor tree)
	/usr/lib/golang/src/encoding (from $GOROOT)
	/root/go/src/encoding (from $GOPATH)
vendor/github.com/google/go-containerregistry/pkg/authn/basic.go:18:2: cannot find package "encoding/base64" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/encoding/base64 (vendor tree)
	/usr/lib/golang/src/encoding/base64 (from $GOROOT)
	/root/go/src/encoding/base64 (from $GOPATH)
vendor/github.com/spf13/pflag/string_slice.go:5:2: cannot find package "encoding/csv" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/encoding/csv (vendor tree)
	/usr/lib/golang/src/encoding/csv (from $GOROOT)
	/root/go/src/encoding/csv (from $GOPATH)
vendor/github.com/google/go-containerregistry/pkg/v1/hash.go:19:2: cannot find package "encoding/hex" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/encoding/hex (vendor tree)
	/usr/lib/golang/src/encoding/hex (from $GOROOT)
	/root/go/src/encoding/hex (from $GOPATH)
vendor/github.com/google/go-containerregistry/pkg/v1/remote/error.go:18:2: cannot find package "encoding/json" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/encoding/json (vendor tree)
	/usr/lib/golang/src/encoding/json (from $GOROOT)
	/root/go/src/encoding/json (from $GOPATH)
vendor/github.com/golang/glog/glog.go:76:2: cannot find package "errors" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/errors (vendor tree)
	/usr/lib/golang/src/errors (from $GOROOT)
	/root/go/src/errors (from $GOPATH)
cmd/kritis/kubectl/plugins/resolve/cmd/root.go:20:2: cannot find package "flag" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/flag (vendor tree)
	/usr/lib/golang/src/flag (from $GOROOT)
	/root/go/src/flag (from $GOPATH)
cmd/kritis/kubectl/plugins/resolve/cmd/root.go:21:2: cannot find package "fmt" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/fmt (vendor tree)
	/usr/lib/golang/src/fmt (from $GOROOT)
	/root/go/src/fmt (from $GOPATH)
vendor/github.com/google/go-containerregistry/pkg/v1/hash.go:22:2: cannot find package "hash" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/hash (vendor tree)
	/usr/lib/golang/src/hash (from $GOROOT)
	/root/go/src/hash (from $GOPATH)
vendor/github.com/golang/glog/glog.go:79:2: cannot find package "io" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/io (vendor tree)
	/usr/lib/golang/src/io (from $GOROOT)
	/root/go/src/io (from $GOPATH)
vendor/github.com/google/go-containerregistry/pkg/authn/keychain.go:21:2: cannot find package "io/ioutil" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/io/ioutil (vendor tree)
	/usr/lib/golang/src/io/ioutil (from $GOROOT)
	/root/go/src/io/ioutil (from $GOPATH)
vendor/github.com/golang/glog/glog.go:80:2: cannot find package "log" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/log (vendor tree)
	/usr/lib/golang/src/log (from $GOROOT)
	/root/go/src/log (from $GOPATH)
vendor/gopkg.in/yaml.v2/decode.go:8:2: cannot find package "math" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/math (vendor tree)
	/usr/lib/golang/src/math (from $GOROOT)
	/root/go/src/math (from $GOPATH)
vendor/github.com/spf13/pflag/ip.go:5:2: cannot find package "net" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/net (vendor tree)
	/usr/lib/golang/src/net (from $GOROOT)
	/root/go/src/net (from $GOPATH)
vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/basic.go:18:2: cannot find package "net/http" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/net/http (vendor tree)
	/usr/lib/golang/src/net/http (from $GOROOT)
	/root/go/src/net/http (from $GOPATH)
vendor/github.com/google/go-containerregistry/pkg/name/registry.go:17:8: cannot find package "net/url" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/net/url (vendor tree)
	/usr/lib/golang/src/net/url (from $GOROOT)
	/root/go/src/net/url (from $GOPATH)
vendor/github.com/golang/glog/glog.go:81:2: cannot find package "os" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/os (vendor tree)
	/usr/lib/golang/src/os (from $GOROOT)
	/root/go/src/os (from $GOPATH)
vendor/github.com/google/go-containerregistry/pkg/authn/helper.go:21:2: cannot find package "os/exec" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/os/exec (vendor tree)
	/usr/lib/golang/src/os/exec (from $GOROOT)
	/root/go/src/os/exec (from $GOPATH)
vendor/github.com/golang/glog/glog_file.go:26:2: cannot find package "os/user" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/os/user (vendor tree)
	/usr/lib/golang/src/os/user (from $GOROOT)
	/root/go/src/os/user (from $GOPATH)
vendor/github.com/google/go-containerregistry/pkg/authn/keychain.go:24:2: cannot find package "path" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/path (vendor tree)
	/usr/lib/golang/src/path (from $GOROOT)
	/root/go/src/path (from $GOPATH)
vendor/github.com/golang/glog/glog.go:82:2: cannot find package "path/filepath" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/path/filepath (vendor tree)
	/usr/lib/golang/src/path/filepath (from $GOROOT)
	/root/go/src/path/filepath (from $GOPATH)
vendor/gopkg.in/yaml.v2/decode.go:9:2: cannot find package "reflect" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/reflect (vendor tree)
	/usr/lib/golang/src/reflect (from $GOROOT)
	/root/go/src/reflect (from $GOPATH)
vendor/github.com/google/go-containerregistry/pkg/v1/remote/transport/scheme.go:18:2: cannot find package "regexp" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/regexp (vendor tree)
	/usr/lib/golang/src/regexp (from $GOROOT)
	/root/go/src/regexp (from $GOPATH)
vendor/github.com/golang/glog/glog.go:83:2: cannot find package "runtime" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/runtime (vendor tree)
	/usr/lib/golang/src/runtime (from $GOROOT)
	/root/go/src/runtime (from $GOPATH)
vendor/gopkg.in/yaml.v2/encode.go:9:2: cannot find package "sort" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/sort (vendor tree)
	/usr/lib/golang/src/sort (from $GOROOT)
	/root/go/src/sort (from $GOPATH)
vendor/github.com/golang/glog/glog.go:84:2: cannot find package "strconv" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/strconv (vendor tree)
	/usr/lib/golang/src/strconv (from $GOROOT)
	/root/go/src/strconv (from $GOPATH)
vendor/github.com/golang/glog/glog.go:85:2: cannot find package "strings" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/strings (vendor tree)
	/usr/lib/golang/src/strings (from $GOROOT)
	/root/go/src/strings (from $GOPATH)
vendor/github.com/golang/glog/glog.go:86:2: cannot find package "sync" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/sync (vendor tree)
	/usr/lib/golang/src/sync (from $GOROOT)
	/root/go/src/sync (from $GOPATH)
vendor/github.com/golang/glog/glog.go:87:2: cannot find package "sync/atomic" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/sync/atomic (vendor tree)
	/usr/lib/golang/src/sync/atomic (from $GOROOT)
	/root/go/src/sync/atomic (from $GOPATH)
vendor/github.com/spf13/cobra/cobra.go:25:2: cannot find package "text/template" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/text/template (vendor tree)
	/usr/lib/golang/src/text/template (from $GOROOT)
	/root/go/src/text/template (from $GOPATH)
vendor/github.com/golang/glog/glog.go:88:2: cannot find package "time" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/time (vendor tree)
	/usr/lib/golang/src/time (from $GOROOT)
	/root/go/src/time (from $GOPATH)
vendor/gopkg.in/yaml.v2/sorter.go:5:2: cannot find package "unicode" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/unicode (vendor tree)
	/usr/lib/golang/src/unicode (from $GOROOT)
	/root/go/src/unicode (from $GOPATH)
vendor/github.com/google/go-containerregistry/pkg/name/check.go:19:2: cannot find package "unicode/utf8" in any of:
	/root/go/src/github.com/grafeas/kritis/vendor/unicode/utf8 (vendor tree)
	/usr/lib/golang/src/unicode/utf8 (from $GOROOT)
	/root/go/src/unicode/utf8 (from $GOPATH)

Has anyone encountered this kind of problem? Can you tell me how to solve it?

**Comment by aysylu** [comment]
@codingandcoding: just to confirm, you were able to resolve this, correct?
