### ISSUE TITLE
Add support for the separation of noteReference and occurrenceReference

### ISSUE THREAD

**Issue by marco-lancini** [grafeas/kritis#401]
## Feature Request
Building on Issue #396, it would be good to extend Kritis so to add support for the separation of `noteReference` and `occurrenceReference`. This will also help lining up with the [multi project setup](https://cloud.google.com/binary-authorization/docs/multi-project-setup-cli) supported by BinAuth

## Proposed Solution
* Extend the definition of `ImageSecurityPolicy` and `GenericAttestationPolicy` so to introduce a new field named `occurrenceReference`:
    - `noteReference`: will point to the project where the Attestor is placed. Example: `noteReference: v1beta1/projects/project-attestor/notes/build-attestor`
   - `occurrenceReference`: will point to the project where the Occurrences will be placed. Example: `occurrenceReference: v1beta1/projects/project-occurrence/occurrences`

* Update documentation to include this use case, whereby an additional service account will be needed if `noteReference` and `occurrenceReference` differ
* Update examples to include the new field

**Comment by aysylu** [comment]
Hey @marco-lancini, my understanding from our conversation today was that we'll put the new `occurrenceReference` field to `ImageSecurityPolicy` and `GenericAttestationPolicy`. Did something change on your end to end up with this proposal?

**Comment by marco-lancini** [comment]
Hey @aysylu, you are correct! I edited the description of this issue to reflect this.
Thanks for pointing this out

**Comment by marco-lancini** [comment]
Hi @aysylu, after considering this further today while planning the required changes, we were wondering if it could be more convenient to attach the new `occurrenceReference` field directly to an `AttestationAuthority`, rather than to ISPs/GAPs.

As the `AttestationAuthority` is used by both ISPs and GAPs, adding the new field to `AttestationAuthority` would enable separation of note and occurrences for both ISPs and GAPs.

In this way we would also prevent the de-duplication of the code related to the verification logic that we will have to introduce in the other case. For example, `findUnsatisfiedAuths` [1] would have to be extended to support both the `v1beta1.ImageSecurityPolicy` and `v1beta1.GenericAttestationPolicy` types distinctly.

[1] `findUnsatisfiedAuths`: https://github.com/grafeas/kritis/blob/22bf0899396a6b164253193421e6cbacc2fc3dcf/pkg/kritis/review/review.go#L146

**Comment by aysylu** [comment]
Hi @marco-lancini, thank you for filing this issue and the discussion! That's a great question. I could see this go either way, so let me think about this. Let's also get a perspective from @nenaddedic who's working on BinAuthz.

**Comment by nenaddedic** [comment]
@marco-lancini This seems to be a bug in Kritis implementation.

Grafeas has the ListNoteOccurrences method [1] which returns all Occurrences attached to a Note (subject to access restrictions).  Returned Occurrences may be in multiple projects.  Kritis should use this method instead of ListOccurrences [2] which is scoped to a single project.  I think this would address your concern, because noteReference would be fully respected when fetching the Occurrences during attestor evaluation.

So specifically: I propose to change the code in [2] to use ListNoteOccurrences, where nID (the ID of the Note occurrences to fetch) is set to noteReference found in the attestor.

Does this sound right to you?

[1] https://github.com/grafeas/grafeas/blob/master/go/v1/api/grafeas.go#L96
[2] https://github.com/grafeas/kritis/blob/22bf0899396a6b164253193421e6cbacc2fc3dcf/pkg/kritis/metadata/containeranalysis/containeranalysis.go#L104

**Comment by marco-lancini** [comment]
Hi @nenaddedic,
thanks for your input. I'm trying to modify the `fetchOccurrence` as below:

```
req := &grafeas.ListNoteOccurrencesRequest{
	Name: "projects/project-attestor/notes/build-attestor-note",
	Filter:    fmt.Sprintf("resource_url=%q AND kind=%q", util.GetResourceURL(containerImage), kind),
	PageSize:  constants.PageSize,
	PageToken: "0",
}

it := c.client.ListNoteOccurrences(c.ctx, req)
```

But I'm facing the following error:

```
E1007 10:35:05.673599       1 validating_transport.go:57] rpc error: code = InvalidArgument desc = Request contains an invalid argument.
E1007 10:35:05.673625       1 review.go:151] Error fetching validated attestations for eu.gcr.io/project-gcr/<path>/alpine@sha256:<hash>: rpc error: code = InvalidArgument desc = Request contains an invalid argument.
```

After trial and error, this seems to be related to the `Filter` field, which is although expected as defined in https://github.com/grafeas/grafeas/blob/master/proto/v1beta1/grafeas.proto#L440.

Any suggestions?

**Comment by nenaddedic** [comment]
It is fine to drop the kind clause from the filter.  In fact filtering by kind is somewhat incorrect when using ListNoteOccurrences, because Occurrences attached to a Note must be of the same kind as the Note.

This said, verifying that the Note is of the Attestation kind would be good.

**Comment by nenaddedic** [comment]
If you already have a PR, feel free to send it for review.  I opened https://github.com/grafeas/kritis/issues/405 to track.

**Comment by marco-lancini** [comment]
Hi @nenaddedic and @aysylu,
I've updated PR #399 to reflect this. I'd be grateful if you could review and approve it!

**Comment by aysylu** [comment]
This has now been [released](https://groups.google.com/forum/#!topic/kritis-users/RuMzxvoqkhw) as part of `v0.2.0`. Thanks for your valuable contribution and patience!

Please feel free to re-open this issue if it's not fully addressed in the new release.
