### ISSUE TITLE
Fetching attestations ignores AttestationAuthority.NoteReference

### ISSUE THREAD

**Issue by nenaddedic** [grafeas/kritis#405]
## Expected Behavior

When fetching attestation Occurrences for an AttestationAuthority auth, all ATTESTATION Occurrences attached to the Note auth.NoteReference should be fetched.

## Actual Behavior
All ATTESTATION Occurrences within the image project are fetched.  This is in one sense too narrow (there could be Occurences outside of the image project), and in another sense too broad (this could contain Occurrences that are not attached to auth.NoteReference).

https://github.com/grafeas/kritis/blob/22bf0899396a6b164253193421e6cbacc2fc3dcf/pkg/kritis/metadata/containeranalysis/containeranalysis.go#L104
should use ListNoteOccurrences instead, and NoteReference should be passed from the AttestationAuthority.

**Comment by aysylu** [comment]
Released this in [0.2.0](https://groups.google.com/forum/#!topic/kritis-users/RuMzxvoqkhw).

**Comment by aysylu** [comment]
Related to #401, #396, and #374
