### ISSUE TITLE
IsFixAvailable crashes when vulnerability FixedLocation is not specified

### ISSUE THREAD

**Issue by liron-l** [grafeas/kritis#415]
## Expected Behavior
No crash

## Actual Behavior
Crash (see [here](https://github.com/grafeas/kritis/blob/1fbdd89727c00724cd794bf8124be33e7e4bc6ea/pkg/kritis/util/util.go#L47)):
```go
func IsFixAvailable(pis []*vulnerability.PackageIssue) bool {
	for _, pi := range pis {
		if pi.GetFixedLocation().GetVersion().Kind == pkg.Version_MAXIMUM {
			// If FixedLocation.Version.Kind = MAXIMUM then no fix is available. Return false
			return false
		}
	}
	return true
}
```
`GetFixedLocation()` and `GetVersion()` can return `nil`. 
Those values are not verified when populating occurrences in Grafeas; also, not all vulnerability occurrences has fixes so i think it's valid keeping this field `nil` instead of specifying a fake value (`Version_MAXIMUM`).

## Steps to Reproduce the Problem
Populate Grafeas with vulnerability occurrences without fixed version
```go
PackageIssue: []*vulnerability.PackageIssue{
				{

					AffectedLocation: &vulnerability.VulnerabilityLocation{CpeUri: "cpe", Package: vuln.Package(),
						Version: &_package.Version{Name: vuln.PackageVersion, Kind: _package.Version_NORMAL}},
					FixedLocation: nil,
					SeverityName: vuln.Severity},
			},
```

**Comment by aysylu** [comment]
Thanks for reporting the issue @liron-l! That's a very good catch. Contributions from the community members to fix this are welcome!

**Comment by ooq** [comment]
Hi @liron-l , I created a patch in #431 , can you take a look if it addresses your issue? Thanks.
