### ISSUE TITLE
Image whitelisting not supported for GAPs

### ISSUE THREAD

**Issue by marco-lancini** [grafeas/kritis#417]
## Expected Behavior

As spcified by the BinAuth documentation, [whitelisting of images](https://cloud.google.com/binary-authorization/docs/policy-yaml-reference#admissionwhitelistpatterns) should be possible for every kind of Policy.

## Actual Behavior

Currently, whitelisting of images is supported only for the `ImageSecurityPolicy` type of policy.

## Proposed Solution

Add and `imageAllowlist` field to the `spec` of a `GenericAttestationPolicy`,
and bypass attestations validation if the target image has been whitelisted.

I'll push a PR to address this shortly

**Comment by ooq** [comment]
Hi @marco-lancini, thanks for reporting this issue. This will be supported as part of compatibility changes with Binary Authorization, and the PR for ISP whitelisting support is out with #409

**Comment by ooq** [comment]
I believe this is fixed now in #409 . Closing.
