### ISSUE TITLE
Figure out client correctly goes through all pages in ListNoteOccurrences call

### ISSUE THREAD

**Issue by aysylu** [grafeas/kritis#419]
## Expected Behavior
The client iterates over all pages using  [next_page_token](https://github.com/grafeas/grafeas/blob/master/proto/v1beta1/grafeas.proto#L334)

## Actual Behavior
The client code just returns an iterator: [link](https://godoc.org/cloud.google.com/go/containeranalysis/apiv1beta1#GrafeasV1Beta1Client.ListNoteOccurrences).

## Additional info
This issue is to verify the pagination is handled correctly on the client.

**Comment by ooq** [comment]
I think this is fixed. Closing.
