### ISSUE TITLE
'signature' field in an Attestation Occurrence should be base64 encoded

### ISSUE THREAD

**Issue by nenaddedic** [grafeas/kritis#427]
## Expected Behavior
occurrence.attestation.attestation.pgpSignedAttestation.signature should be base64 encoded.  In particular:
- ISP should create base64 encoded signatures
- both ISP and GAP should expect base64 encoded signatures

This is both consistent with Binary Authorization (see [1]), and easier to use because it is otherwise difficult to deal with proper formatting of PGP armor.

## Actual Behavior
'signature' field is assumed to be PGP armor without any further encoding.

## Steps to Reproduce the Problem
I believe that problems described in [2] are caused by this.

[1] https://cloud.google.com/binary-authorization/docs/making-attestations
[2] https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kritis-users/atVVPZmzs24/xyb-oKvYAAAJ

**Comment by Tharun-Sabbu** [comment]
Hello, I'm having the exact same issue. I was using standalone setup, can you please release a version with this fix. 

And also I had few other issues with helm chart for kritis (Kritis Helm Chart v0.1.0), I'm on Kubernetes Version 1.15.5 and using helm v2.16.1. Preinstall pod was failing each time with different errors when I try to install chart:

> time="2020-01-03T03:44:53Z" level=info msg="[kubectl apply -f -]"
time="2020-01-03T03:44:53Z" level=info
time="2020-01-03T03:44:53Z" level=error msg="error: SchemaError(io.k8s.api.apps.v1beta2.ReplicaSet): invalid object doesn't have additional properties\n"
time="2020-01-03T03:44:53Z" level=fatal msg="exit status 1"

> time="2020-01-03T06:34:18Z" level=info msg="[kubectl apply -f -]"
time="2020-01-03T06:34:18Z" level=info
time="2020-01-03T06:34:18Z" level=error msg="error: SchemaError(io.k8s.api.apps.v1beta2.ScaleSpec): invalid object doesn't have additional properties\n"
time="2020-01-03T06:34:18Z" level=fatal msg="exit status 1"


To overcome this issue, I had to disable preinstall and postinstall. Then convert Go lang to shell scripts.

**Comment by ooq** [comment]
This issue will be reverted.

Notes on the issue in [2]:
Signature field in attestation is a string type in [v1beta1 API](https://github.com/grafeas/grafeas/blob/master/proto/v1beta1/attestation.proto#L39), so it should not be base64 encoded.
Signature field is bytes type in [v1 API](https://github.com/grafeas/grafeas/blob/master/proto/v1/common.proto#L83), and it should be base64 encoded before putting into a json struct.

[2] https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/kritis-users/atVVPZmzs24/xyb-oKvYAAAJ
