### ISSUE TITLE
"hack/boilerplate.sh" is broken

### ISSUE THREAD

**Issue by ooq** [grafeas/kritis#430]
## Expected Behavior
"hack/boilerplate.sh" should run without error.

## Actual Behavior
Links to the relevant code, snippets
```
hack/boilerplate.sh 
Boilerplate missing in:
././test.sh
```
## Steps to Reproduce the Problem

Environment, commands

1.  
2.  
3.  
4.  

## Additional info
Add any other context about the problem here (e.g. screenshots, links)

**Comment by aysylu** [comment]
The `hack/boilerplate.sh` runs to ensure the necessary boilerplate header was added to each file. For each format, you can see what headers it expects: [link](https://github.com/grafeas/kritis/tree/master/hack/boilerplate).

Is there something else that's broken there?

**Comment by ooq** [comment]
Sorry this is actually a local bug. Closing.
