### ISSUE TITLE
race condition caused integration test to be flaky

### ISSUE THREAD

**Issue by liuplgtm** [grafeas/kritis#495]
## Expected Behavior
the integration test being stable. 

## Actual Behavior
the integration test fails occasionally which shows it is flaky.

The reason is due to a race condition use-before-creation.
basically, the secrets "tls-webhook-secret-bef358dd" is used before it is created properly.

## Steps to Reproduce the Problem

1.  ➜  kritis git:(master) GCP_PROJECT=kritis-int-test make integration-in-docker

See more details below. Note the bold fonts. 
run_test.go:328: setup: installing kritis with image version 127dbfe6d4751ff76b54743b873f70a702e9c8d5 in namespace bef358dd...
    run_test.go:328: install: helm failure: Running [helm install ../kritis-charts --wait -...]: stdout , stderr: Error: release jaundiced-lamb failed: timed out waiting for the condition
        , err: exit status 1: exit status 1
 **HERE IS THE USE: AT 21:18:49**
        preinstall: time="2020-04-22T21:18:49Z" level=info msg="contents of /var/run/secrets/kubernetes.io/serviceaccount/namespace: bef358dd"
        time="2020-04-22T21:18:49Z" level=info msg="running preinstall\nversion v0.2.2\ncommit: 127dbfe6d4751ff76b54743b873f70a702e9c8d5"
        Error from server (NotFound): certificatesigningrequests.certificates.k8s.io "tls-webhook-secret-cert-bef358dd" not found
        Error from server (NotFound): secrets "tls-webhook-secret-bef358dd" not found
**HERE IS THE CREATION OF THE SECRETS, AT 21:18:50**
        time="2020-04-22T21:18:50Z" level=info msg="[cfssl genkey -]"
        time="2020-04-22T21:18:50Z" level=info msg="[cfssljson -bare server]"
        time="2020-04-22T21:18:50Z" level=info
        apiVersion: certificates.k8s.io/v1beta1
        kind: CertificateSigningRequest
        metadata:
            name: tls-webhook-secret-cert-bef358dd
            labels:
                kritis.grafeas.io/install: ""
        time="2020-04-22T21:18:50Z" level=info msg="[kubectl apply -f -]"
        time="2020-04-22T21:18:50Z" level=info msg="certificatesigningrequest.certificates.k8s.io/tls-webhook-secret-cert-bef358dd created\n"
        time="2020-04-22T21:18:50Z" level=info msg="[kubectl certificate approve tls-webhook-secret-cert-bef358dd]"

**Comment by liuplgtm** [comment]
my (irresponsible) guess is that the problem happens here: 
https://github.com/grafeas/kritis/blob/59dc5319561178c7c7d5fe06c38c429f7330322b/helm-hooks/preinstall/preinstall.go#L162

func waitForCSR() string 
this function waits for certificate but it is not very patient:
it checks for certificates every 10 ms and repeats this for 20 times, that is, it waits only for 200ms which is 0.2 seconds.

According to the log above, it could take 1 second for the certificate to be generated:
21:18:50- 21:18:49 = 1 second.

**Comment by ooq** [comment]
I actually couldn't see error message`csr wasn't generated in time` in the log.

btw, when I run `integration-in-docker`, I ran into this issue https://github.com/grafeas/kritis/pull/497, not sure if it's related.

**Comment by liuplgtm** [comment]
the patch in #497 also fixes the problem here. 
nice patch.
