### ISSUE TITLE
Determine who is responsible for checking the Attestation payload

### ISSUE THREAD

**Issue by acamadeo** [grafeas/kritis#503]
Currently, `VerifyAttestation` both verifies an Attestation's signature and checks the contents of the Attestation's payload for the correct image digest. 

1. Determine if `VerifyAttestation` should be doing both things. If not, what information should it return to the user? Should it return the raw extracted payload? Should it return an `AuthenticatedAttestation` (which may provide type-safety for trustworthy Attestation contents)?

2. Determine whether we want to provide any API at all for checking the content's of an Attestation's payload. If so, what would this look like?

**Comment by ooq** [comment]
Thanks for documenting this!

**Comment by acamadeo** [comment]
1. In the next iteration of the crypto library, `VerifyAttestation` should convert an attestation into an `AuthenticatedAttestation` and return it. It should not check the contents of the attestation or `AuthenticatedAttestation`. That will be the responsibility of the caller.

2. It may be helpful to design a `policylib` library built on top of `cryptolib`, which would provide some sort of payload content checking options. This is not necessary at the moment, and cannot be fully fleshed out until rich attestations exist.
