### ISSUE TITLE
Write end-to-end tests for cryptolib's PGP implementation

### ISSUE THREAD

**Issue by acamadeo** [grafeas/kritis#520]
These tests should only use the cryptolib's public API:

For signing:
`NewPgpSigner` and `CreateAttestation`

For verifying:
`NewVerifier` and `VerifyAttestation`

**Comment by liufangwai** [comment]
in method 'CreateAttestation ' , Why Does the Generated Signature Contain Payload Encryption?  I noticed that  the payload plaintext can be restored when verifying the signature , according to the following code:
       messageDetails, err := openpgp.ReadMessage(armorBlock.Body, keyring, nil, nil)
	if err != nil {
		return nil, errors.Wrap(err, "error reading armor signature")
	}

	// MessageDetails.UnverifiedBody signature is not verified until we read it.
	// This will call PublicKey.VerifySignature for the keys in the keyring.
	payload, err := ioutil.ReadAll(messageDetails.UnverifiedBody)
	if err != nil {
		return nil, errors.Wrap(err, "error reading message contents")
	}

**Comment by ooq** [comment]
This is to be compatible with "attached payload" format that is used in grafeas v1beta1 proto.

**Comment by ooq** [comment]
@acamadeo I believe this issue is fixed, correct?

**Comment by liufangwai** [comment]
> @acamadeo I believe this issue is fixed, correct?

Yes, this issue is fixed ,

**Comment by acamadeo** [comment]
Apologies for the late response, just returning from holiday break. Yes this issue is fixed, so I'll close it. Feel free to reopen if there's any outstanding questions!
