### ISSUE TITLE
Automated check and sign on completion of an analysis of an image in GCR

### ISSUE THREAD

**Issue by mvanholsteijn** [grafeas/kritis#586]
**Is your feature request related to a problem? Please describe.**
I want to be able to automatically add an attestation for any GCR image after its vulnerability scan is completed.

**Describe the solution you'd like**

- a cloud run service
- subscribing to the topic `container-analysis-occurrences-v1`
- on each DISCOVERY occurrence in the status completed, validate the scan against the policy

**Describe alternatives you've considered**
I considered writing a little cloud run service to handle the pubsub event and in turn, invoking the signer. This would result in a bigger container runtime.

**Additional context**

**Comment by mvanholsteijn** [comment]
I submitted a pull request to solve this issue -> 
https://github.com/grafeas/kritis/pull/587

**Comment by ooq** [comment]
Thanks @mvanholsteijn for the PR! I'll take a look.

**Comment by mvanholsteijn** [comment]
I can actually provide you  with a terraform template to see this one in action. Are you interested?

**Comment by mvanholsteijn** [comment]
I made the service entirely configurable through environment variables, which allows for the container image to be used without modification.

**Comment by mvanholsteijn** [comment]
Checkout my blog on the subject https://binx.io/blog/2020/11/29/how-to-automate-the-kritis-signer-on-google-cloud-platform/

**Comment by ooq** [comment]
@mvanholsteijn Hi Mark, this is very exciting stuff! Sorry for the delay due to holidays. If you want to update the PR with terraform scripts, I'll review them together.

**Comment by mvanholsteijn** [comment]
@ooq, I think I will leave out the terraform template for now. It is quite elaborate: I will see if I can turn it into a tf module instead.
