### ISSUE TITLE
namespace all the labels/annotations

### ISSUE THREAD

**Issue by dlorenc** [grafeas/kritis#63]
We should namespace all the labels and annotations with something like:

kritis.grafeas.io/<key>

**Comment by priyawadhwa** [comment]
So when users add a breakglass annotation, they can specify it as:

`kritis.grafeas.io:breakglass`

and when we add labels/annotations to a pod it will look like:

`kritis.grafeas.io.invalidImageSecPolicy: [more details]`?

**Comment by dlorenc** [comment]
We chatted earlier, but the exact format should be something like:

```shell
kritis.grafeas.io/breakglass: reason for breaking glass
```
