### ISSUE TITLE
master_merge cloudbuild.yaml build triggers are failing

### ISSUE THREAD

**Issue by aaron-prindle** [grafeas/kritis#69]
currently the cloudbuild.yaml builds are failing and not creating the artifacts for each merge, i believe this is do the the docker image not having all the build deps required for kritis

**Comment by priyawadhwa** [comment]
I think this should (hopefully!) be fixed by #65

**Comment by priyawadhwa** [comment]
fixed with #71 as well. builds are passing now, so closing this issue :)
