### ISSUE TITLE
Create a Release for Kritis.

### ISSUE THREAD

**Issue by tejal29** [grafeas/kritis#96]
This is a Tracking issue for creating kritis release.
DRAFT already started by @tejal29
https://github.com/grafeas/kritis/releases/edit/untagged-25bedf8d6894d660f7d7

- [x] Tar the kritis-charts along with install-script.
- [x] Tar the kubectl resolve plugin along with its plugin.yaml

**Comment by dlorenc** [comment]
Instead of tar'ing the chart we should create a `helm package`

**Comment by tejal29** [comment]
noted

**Comment by tejal29** [comment]
Check krew for plugin!

**Comment by aaron-prindle** [comment]
Now kritis is a single helm chart so the release can be a single tar file.  I have setup a kritis-charts repository at https://storage.googleapis.com/kritis-charts/repository/ which will contain all releases.
